spring.datasource.url: jdbc:mysql://dell:3306/blog
spring.datasource.username: root
spring.datasource.password: password
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.show-sql: false

blog.title: "DevPub"
blog.subtitle: "Рассказы хмельных единорогов"
blog.phone: "+77776543210"
blog.email: "ssngg@yandex.ru"
blog.copyright: "Никита Стоян"
blog.copyrightFrom: "2020"

spring.flyway.enabled: true
