spring.datasource.url: jdbc:mysql://192.168.1.16:3306/blog
spring.datasource.username: root
spring.datasource.password: password
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.show-sql: false

blog.title: "DevPub"
blog.subtitle: "Рассказы хмельных единорогов"
blog.phone: "+77776543210"
blog.email: "ssngg@yandex.ru"
blog.copyright: "Никита Стоян"
blog.copyrightFrom: "2020"

# lifetime in minutes
blog.captcha.lifetime: 60
# image size in minutes
blog.captcha.captcha.height: 35
blog.captcha.captcha.width: 100
# characters count
blog.captcha.captcha.length: 6

spring.flyway.enabled: true
