spring.datasource.url: jdbc:mysql://${db.host}:3306/${db.name}
db.host: ${DB_HOST:192.168.1.16}
db.name: ${DB_NAME:blog}
spring.datasource.username: ${DB_USER:root}
spring.datasource.password: ${DB_PASSWORD:password}
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.show-sql: false

blog.title: Deep Prank
blog.subtitle: Trash Book
blog.phone: +77776543210
blog.email: bloqsng@gmail.com
blog.copyright: Nikita Stoyan
blog.copyrightFrom: 2021

# lifetime in minutes
blog.captcha.lifetime: 60
# image size in minutes
blog.captcha.captcha.height: 35
blog.captcha.captcha.width: 100
# characters count
blog.captcha.captcha.length: 6

spring.flyway.enabled: true

# uploading files
spring.servlet.multipart.max-file-size: 1MB
spring.servlet.multipart.max-request-size: 1MB
spring.servlet.multipart.enabled: true
spring.servlet.multipart.location: ${java.io.tmpdir}
upload.path: D:\junk\img

# sending mails
spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: bloqsng
spring.mail.password: ${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true