INSERT INTO tags (id, name) VALUES(1, "Java" );
INSERT INTO tags (id, name) VALUES(2, "Alcohol" );
INSERT INTO tags (id, name) VALUES(3, "Chaos" );
INSERT INTO tags (id, name) VALUES(4, "F1" );
INSERT INTO tags (id, name) VALUES(5, "Drama" );
INSERT INTO tag2post (id, post_id, tag_id) VALUES(1, 10, 1);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(2, 7, 1);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(3, 9, 1);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(4, 12, 1);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(5, 22, 1);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(6, 14, 1);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(7, 1, 1);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(8, 6, 1);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(9, 5, 1);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(11, 3, 1);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(12, 17, 1);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(13, 16, 1);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(14, 18, 1);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(15, 20, 1);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(16, 11, 1);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(10, 3, 2);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(17, 5, 2);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(18, 6, 2);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(19, 7, 2);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(20, 22, 2);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(21, 20, 2);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(22, 16, 2);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(23, 18, 3);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(24, 20, 3);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(25, 5, 3);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(26, 5, 4);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(27, 7, 4);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(28, 9, 4);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(29, 10, 4);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(30, 16, 4);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(31, 14, 4);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(32, 17, 4);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(33, 18, 4);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(34, 20, 4);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(35, 22, 4);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(36, 6, 4);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(37, 3, 5);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(38, 12, 5);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(39, 21, 5);
INSERT INTO tag2post (id, post_id, tag_id) VALUES(40, 8, 5);


